name = "silly pack :3"
author = "nano"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e12d1d77b331f68488a0e234735321768a3ac085eae0050284cbd42e54695f21"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
