name = "le transgenre femme autiste"
author = "nano"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c74b3d28a31d1a4237b27cf1f2559878c57c1b645c262a35b2d1299969ca7465"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
