name = "le transgenre femme autiste"
author = "nano"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "827298e382c350a153ddaf25623e2265092dd441aba6d08084e5da7b6c87b5e2"

[versions]
fabric = "0.14.23"
minecraft = "1.20.1"
