name = "nanomon"
author = "nano"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9eec58768361fdb37440612d537229bd0cf9c468c91f569b22729dbdaddb264"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
