enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = false
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 64.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
cobblemon = true
minecraft = true
visualoverhaul = true
